In [1]:
import pandas as pd

In [22]:
fetch  = pd.read_csv("/Users/yanis/Portfolio Opt/F-F_Research_Data_Factors.csv", index_col=0, parse_dates=True,skiprows=2).iloc[:1187]
fetch.index = pd.to_datetime(fetch.index, format="%Y%m").to_period('M')
fetch

/var/folders/_v/hbm3rz4x403fj9qwqn8wddhr0000gn/T/ipykernel_60297/2344957497.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  fetch  = pd.read_csv("/Users/yanis/Portfolio Opt/F-F_Research_Data_Factors.csv", index_col=0, parse_dates=True,skiprows=2).iloc[:1187]

        Mkt-RF    SMB    HML    RF
1926-07   2.89  -2.55  -2.39  0.22
1926-08   2.64  -1.14   3.81  0.25
1926-09   0.38  -1.36   0.05  0.23
1926-10  -3.27  -0.14   0.82  0.32
1926-11   2.54  -0.11  -0.61  0.31
...        ...    ...    ...   ...
2025-01   2.80  -1.97   1.63  0.37
2025-02  -2.44  -5.79   4.91  0.33
2025-03  -6.39  -2.76   2.90  0.34
2025-04  -0.84  -0.59  -3.40  0.35
2025-05   6.06   0.70  -2.88  0.38

[1187 rows x 4 columns]

In [23]:
fetch.to_csv("FF_Monthly_Data.csv")
fetch.head()

Données sauvegardées dans FF_Monthly_Data.csv
Nombre de lignes: 1187
Période: 1926-07 à 2025-05
Colonnes: ['Mkt-RF', 'SMB', 'HML', 'RF']

Aperçu des données:

        Mkt-RF    SMB    HML    RF
1926-07   2.89  -2.55  -2.39  0.22
1926-08   2.64  -1.14   3.81  0.25
1926-09   0.38  -1.36   0.05  0.23
1926-10  -3.27  -0.14   0.82  0.32
1926-11   2.54  -0.11  -0.61  0.31